

# site icon
favicon: /favicon.png

# author headimg
headimg: http://oct8d1mqf.bkt.clouddn.com/2016-10-17-15%3A42%3A28.jpg

# search
search: 
    enable: true
    placeholder: Enter Key...

# sidebar
sidebar: 
  enable: true
  menus:
    -
      name: Weibo
      link: http://weibo.com/yumemor/
      target: _blank

# comments
comments:
  duoshuo_username:  yumemor
  #disqus_username: yumemor

# accounts support weibo/github/zhihu/twitter/douban 
# display to former three
social: 
  -
    name: weibo
    link: http://weibo.com/yumemor/
  -
    name: github
    link: https://github.com/yumemor
  -
    name: zhihu
    link: https://www.zhihu.com/people/yumemor
#  -
#    name: twitter
#    link: 
#  -
#    name: douban
#    link: 





