baseurl: /
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title.html
auto: true
paginate: 6
paginate_path: page/:num

blog:
    name: Canjia                                        # 博客名称
    description: 一起都会好起来.                                        # 博客描述
    title:                                               # 网页标题
    url: http://xucanjia.github.io                        # 博客地址
    duoshuo: 2121108                                     # 多说ID
    tongji:                                              # 百度统计ID
    qiniu:                                               # 七牛云地址
author:
    name:                                                # 作者名称
    email:                                               # 邮箱地址
    weibo:                                               # 微博地址
    github: https://github.com/xucanjia
    logo: /res/img/me.jpg                                # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key
